# Generated by Django 5.2.5 on 2025-08-17 23:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveContentPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable pattern name", max_length=100)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("pii_detected", "Personal Identifiable Information"),
                            ("financial_data", "Financial Information"),
                            ("medical_data", "Medical Information"),
                            ("legal_data", "Legal Information"),
                            ("custom_pattern", "Custom Sensitive Pattern"),
                            ("bulk_sharing", "Bulk Sensitive Data Sharing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("regex_pattern", models.TextField(help_text="Regular expression pattern")),
                ("description", models.TextField(blank=True)),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_quarantine",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically quarantine content matching this pattern",
                    ),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
                ("match_whole_words", models.BooleanField(default=True)),
                (
                    "minimum_matches",
                    models.IntegerField(
                        default=1, help_text="Minimum number of matches to trigger violation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sensitive Content Pattern",
                "verbose_name_plural": "Sensitive Content Patterns",
                "ordering": ["-sensitivity_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Scan"),
                            ("automatic", "Automatic Scan"),
                            ("bulk", "Bulk Scan"),
                            ("scheduled", "Scheduled Scan"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                ("violations_found", models.IntegerField(default=0)),
                (
                    "highest_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "scan_score",
                    models.IntegerField(
                        default=0, help_text="Risk score from 0 (safe) to 100 (high risk)"
                    ),
                ),
                (
                    "content_length",
                    models.IntegerField(help_text="Length of scanned content in characters"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(help_text="Processing time in milliseconds"),
                ),
                (
                    "patterns_matched",
                    models.JSONField(default=list, help_text="List of pattern IDs that matched"),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Scan",
                "verbose_name_plural": "Content Scans",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "auto_scan_enabled",
                    models.BooleanField(default=True, help_text="Automatically scan new content"),
                ),
                (
                    "scan_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Minimum sensitivity level to trigger notifications",
                        max_length=10,
                    ),
                ),
                (
                    "notify_on_violations",
                    models.BooleanField(
                        default=True, help_text="Send notifications when violations are found"
                    ),
                ),
                (
                    "notify_on_quarantine",
                    models.BooleanField(
                        default=True, help_text="Send notifications when content is quarantined"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=False, help_text="Send email notifications for moderation events"
                    ),
                ),
                (
                    "auto_quarantine_critical",
                    models.BooleanField(
                        default=False, help_text="Automatically quarantine critical violations"
                    ),
                ),
                (
                    "auto_block_sharing",
                    models.BooleanField(
                        default=True, help_text="Block sharing of content with violations"
                    ),
                ),
                (
                    "custom_sensitive_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User-defined sensitive terms to watch for",
                    ),
                ),
                (
                    "trusted_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domains that are trusted for sharing sensitive content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Settings",
                "verbose_name_plural": "Moderation Settings",
            },
        ),
        migrations.CreateModel(
            name="PolicyViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("pii_detected", "Personal Identifiable Information"),
                            ("financial_data", "Financial Information"),
                            ("medical_data", "Medical Information"),
                            ("legal_data", "Legal Information"),
                            ("custom_pattern", "Custom Sensitive Pattern"),
                            ("bulk_sharing", "Bulk Sensitive Data Sharing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "matched_content",
                    models.TextField(help_text="The actual content that matched (may be redacted)"),
                ),
                ("match_count", models.IntegerField(default=1)),
                (
                    "context_snippet",
                    models.TextField(
                        blank=True, help_text="Surrounding context (with sensitive data redacted)"
                    ),
                ),
                ("start_position", models.IntegerField(blank=True, null=True)),
                ("end_position", models.IntegerField(blank=True, null=True)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "resolution_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_acknowledged", "User Acknowledged"),
                            ("content_modified", "Content Modified"),
                            ("false_positive", "Marked as False Positive"),
                            ("approved_exception", "Approved Exception"),
                            ("content_removed", "Content Removed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="moderation.contentscan",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="moderation.sensitivecontentpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Violation",
                "verbose_name_plural": "Policy Violations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("scan", "Content Scanned"),
                            ("quarantine", "Content Quarantined"),
                            ("notify_user", "User Notified"),
                            ("block_sharing", "Sharing Blocked"),
                            ("require_review", "Manual Review Required"),
                            ("approve", "Content Approved"),
                            ("release", "Content Released"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("quarantined", "Quarantined"),
                            ("blocked", "Blocked"),
                            ("requires_review", "Requires Manual Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for taking this action")),
                (
                    "automated",
                    models.BooleanField(
                        default=True, help_text="Whether action was automated or manual"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this action expires (e.g., quarantine period)",
                        null=True,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("user_acknowledged", models.BooleanField(default=False)),
                (
                    "action_data",
                    models.JSONField(
                        default=dict, help_text="Additional data specific to this action type"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="moderation.contentscan",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "violation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="moderation.policyviolation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentscan",
            index=models.Index(
                fields=["user", "scanned_at"], name="moderation__user_id_83a383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscan",
            index=models.Index(
                fields=["content_type", "object_id"], name="moderation__content_74040d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscan",
            index=models.Index(
                fields=["highest_severity", "scanned_at"], name="moderation__highest_427047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["action_type", "action_status"], name="moderation__action__064384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["triggered_by", "created_at"], name="moderation__trigger_900de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(fields=["expiry_date"], name="moderation__expiry__2bd04b_idx"),
        ),
        migrations.AddIndex(
            model_name="policyviolation",
            index=models.Index(
                fields=["content_scan", "severity"], name="moderation__content_407909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyviolation",
            index=models.Index(
                fields=["violation_type", "created_at"], name="moderation__violati_7531c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyviolation",
            index=models.Index(
                fields=["is_resolved", "severity"], name="moderation__is_reso_daf2a0_idx"
            ),
        ),
    ]
