# Generated by Django 5.2.5 on 2025-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentscan',
            name='content_text',
            field=models.TextField(blank=True, help_text='The scanned content text'),
        ),
        migrations.AddField(
            model_name='policyviolation',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence score of the match (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='policyviolation',
            name='context',
            field=models.TextField(blank=True, help_text='Surrounding context (alias for context_snippet)'),
        ),
        migrations.AddField(
            model_name='policyviolation',
            name='matched_text',
            field=models.TextField(blank=True, help_text='Alias for matched_content (backward compatibility)'),
        ),
        migrations.AlterField(
            model_name='contentscan',
            name='content_length',
            field=models.IntegerField(blank=True, help_text='Length of scanned content in characters', null=True),
        ),
        migrations.AlterField(
            model_name='contentscan',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('quarantined', 'Quarantined'), ('blocked', 'Blocked'), ('flagged', 'Flagged for Review'), ('requires_review', 'Requires Manual Review')], default='pending', max_length=20),
        ),
    ]
