# Generated by Django 5.2.5 on 2025-08-17 19:04

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(help_text="Date of the snapshot")),
                ("total_documents", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("total_forum_posts", models.IntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                (
                    "retention_violations_count",
                    models.IntegerField(
                        default=0, help_text="Items past their intended retention date"
                    ),
                ),
                ("shared_documents_count", models.IntegerField(default=0)),
                ("public_documents_count", models.IntegerField(default=0)),
                ("encrypted_documents_count", models.IntegerField(default=0)),
                (
                    "privacy_score",
                    models.IntegerField(
                        default=0,
                        help_text="Overall privacy score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "security_score",
                    models.IntegerField(
                        default=0,
                        help_text="Security posture score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="analytics_a_user_id_02a715_idx"),
                    models.Index(
                        fields=["date", "privacy_score"], name="analytics_a_date_b8ab2d_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="DataUsageMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("storage", "Storage Usage"),
                            ("activity", "User Activity"),
                            ("sharing", "Data Sharing"),
                            ("retention", "Data Retention"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(help_text="Specific metric being tracked", max_length=100),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "unit",
                    models.CharField(
                        default="count", help_text="Unit of measurement", max_length=20
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metric context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Usage Metric",
                "verbose_name_plural": "Data Usage Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "metric_type", "timestamp"],
                        name="analytics_d_user_id_801a91_idx",
                    ),
                    models.Index(fields=["timestamp"], name="analytics_d_timesta_e8330b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivacyInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("risk", "Privacy Risk"),
                            ("recommendation", "Recommendation"),
                            ("alert", "Alert"),
                            ("tip", "Privacy Tip"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "action_text",
                    models.CharField(
                        blank=True, help_text="Call-to-action button text", max_length=100
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, help_text="URL for the recommended action"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this insight becomes irrelevant", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Insight",
                "verbose_name_plural": "Privacy Insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "is_dismissed"],
                        name="analytics_p_user_id_5d7913_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"], name="analytics_p_severit_0f6871_idx"
                    ),
                    models.Index(fields=["expires_at"], name="analytics_p_expires_a321a7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        help_text="Type of item (document, message, post)", max_length=50
                    ),
                ),
                ("item_id", models.UUIDField(help_text="ID of the item to be deleted")),
                (
                    "item_title",
                    models.CharField(help_text="Human-readable item description", max_length=255),
                ),
                ("scheduled_date", models.DateTimeField(help_text="When deletion is scheduled")),
                (
                    "retention_reason",
                    models.CharField(help_text="Reason for deletion", max_length=100),
                ),
                (
                    "can_extend",
                    models.BooleanField(
                        default=True, help_text="Whether user can extend retention"
                    ),
                ),
                ("is_notified", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_timeline",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Timeline Entry",
                "verbose_name_plural": "Retention Timeline Entries",
                "ordering": ["scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "scheduled_date"], name="analytics_r_user_id_b648ff_idx"
                    ),
                    models.Index(
                        fields=["scheduled_date", "is_completed"],
                        name="analytics_r_schedul_caccb8_idx",
                    ),
                ],
            },
        ),
    ]
