# Generated by Django 5.2.5 on 2025-08-19 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssnapshot",
            name="avg_content_risk_score",
            field=models.FloatField(
                default=0.0, help_text="Average risk score of scanned content (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="analyticssnapshot",
            name="content_violations_found",
            field=models.IntegerField(default=0, help_text="Total privacy violations detected"),
        ),
        migrations.AddField(
            model_name="analyticssnapshot",
            name="critical_violations_count",
            field=models.IntegerField(default=0, help_text="Number of critical privacy violations"),
        ),
        migrations.AddField(
            model_name="analyticssnapshot",
            name="moderation_compliance_score",
            field=models.IntegerField(
                default=100,
                help_text="Content moderation compliance score",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="analyticssnapshot",
            name="quarantined_items_count",
            field=models.IntegerField(default=0, help_text="Number of items currently quarantined"),
        ),
        migrations.AddField(
            model_name="analyticssnapshot",
            name="total_content_scans",
            field=models.IntegerField(
                default=0, help_text="Total number of content scans performed"
            ),
        ),
    ]
