# Generated by Django 5.2.5 on 2025-08-19 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_moderation_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='avg_classification_confidence',
            field=models.FloatField(default=0.0, help_text='Average confidence score of classifications (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='classified_assets_count',
            field=models.IntegerField(default=0, help_text='Number of assets with classification results'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='data_lineage_relationships',
            field=models.IntegerField(default=0, help_text='Number of data lineage relationships tracked'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='discovery_coverage_score',
            field=models.IntegerField(default=0, help_text='Data discovery coverage score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='discovery_insights_count',
            field=models.IntegerField(default=0, help_text='Number of active discovery insights'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='sensitive_assets_count',
            field=models.IntegerField(default=0, help_text='Number of assets classified as sensitive (high/critical)'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='total_data_assets',
            field=models.IntegerField(default=0, help_text='Total number of discovered data assets'),
        ),
    ]
