# Generated by Django 5.2.5 on 2025-10-10 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('soc2', 'SOC2'), ('pci_dss', 'PCI-DSS'), ('iso27001', 'ISO 27001')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Policy',
                'verbose_name_plural': 'Compliance Policies',
                'db_table': 'foundation_compliance_policy',
                'unique_together': {('name', 'framework')},
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_subject_id', models.CharField(help_text='External identifier for the data subject', max_length=255)),
                ('data_subject_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose', models.CharField(help_text='Purpose for which consent was given', max_length=200)),
                ('legal_basis', models.CharField(help_text='Legal basis for processing (e.g., Article 6(1)(a))', max_length=100)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consent_source', models.CharField(help_text='Source where consent was collected (e.g., website, API)', max_length=100)),
                ('consent_method', models.CharField(help_text='Method of consent collection (e.g., checkbox, signature)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'db_table': 'foundation_consent_record',
                'indexes': [models.Index(fields=['data_subject_id'], name='foundation__data_su_fb95d0_idx'), models.Index(fields=['data_subject_email'], name='foundation__data_su_61eb1c_idx'), models.Index(fields=['status'], name='foundation__status_75a813_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('phi', 'Protected Health Information'), ('pii', 'Personally Identifiable Information'), ('payment', 'Payment Card Data')], max_length=20)),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days to retain data')),
                ('retention_action', models.CharField(choices=[('delete', 'Delete'), ('archive', 'Archive'), ('anonymize', 'Anonymize'), ('review', 'Manual Review Required')], default='archive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frameworks', models.ManyToManyField(related_name='retention_policies', to='compliance.compliancepolicy')),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'db_table': 'foundation_data_retention_policy',
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('soc2', 'SOC2'), ('pci_dss', 'PCI-DSS'), ('iso27001', 'ISO 27001')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('remediated', 'Remediated'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=20)),
                ('affected_records', models.JSONField(default=list, help_text='List of affected record IDs')),
                ('remediation_actions', models.TextField(blank=True)),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detected_by', models.CharField(help_text='System or person who detected the violation', max_length=100)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_violations', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='compliance.compliancepolicy')),
                ('remediated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediated_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Violation',
                'verbose_name_plural': 'Compliance Violations',
                'db_table': 'foundation_compliance_violation',
                'indexes': [models.Index(fields=['framework', 'severity'], name='foundation__framewo_df6e01_idx'), models.Index(fields=['status'], name='foundation__status_9b0b55_idx'), models.Index(fields=['detected_at'], name='foundation__detecte_bac33d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_subject_id', models.CharField(max_length=255)),
                ('data_subject_email', models.EmailField(max_length=254)),
                ('data_subject_name', models.CharField(blank=True, max_length=200)),
                ('request_type', models.CharField(choices=[('access', 'Right of Access (Art. 15)'), ('rectification', 'Right to Rectification (Art. 16)'), ('erasure', 'Right to Erasure (Art. 17)'), ('restrict', 'Right to Restrict Processing (Art. 18)'), ('portability', 'Right to Data Portability (Art. 20)'), ('object', 'Right to Object (Art. 21)')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Identity Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('extended', 'Extended (Complex Request)')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dsr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Subject Request',
                'verbose_name_plural': 'Data Subject Requests',
                'db_table': 'foundation_data_subject_request',
                'indexes': [models.Index(fields=['data_subject_email'], name='foundation__data_su_6e817c_idx'), models.Index(fields=['status'], name='foundation__status_0f7abf_idx'), models.Index(fields=['due_date'], name='foundation__due_dat_0dffff_idx')],
            },
        ),
        migrations.CreateModel(
            name='PHIAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('phi_record_id', models.CharField(max_length=255)),
                ('phi_record_type', models.CharField(max_length=100)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('export', 'Export'), ('print', 'Print')], max_length=50)),
                ('access_reason', models.CharField(help_text='Business justification for access', max_length=200)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_break_glass', models.BooleanField(default=False, help_text='Emergency access override used')),
                ('is_authorized', models.BooleanField(default=True, help_text='Whether access was properly authorized')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PHI Access Log',
                'verbose_name_plural': 'PHI Access Logs',
                'db_table': 'foundation_phi_access_log',
                'indexes': [models.Index(fields=['user', 'accessed_at'], name='foundation__user_id_69914d_idx'), models.Index(fields=['phi_record_id'], name='foundation__phi_rec_c55305_idx'), models.Index(fields=['patient_id'], name='foundation__patient_68fa6e_idx'), models.Index(fields=['accessed_at'], name='foundation__accesse_2b41fa_idx')],
            },
        ),
    ]
